# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(default='NA', max_length=5)),
                ('week', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=1)),
                ('rockIslandScore', models.IntegerField(default=0)),
                ('opponentScore', models.IntegerField(default=0)),
                ('rii1st', models.IntegerField(default=0)),
                ('rii2nd', models.IntegerField(default=0)),
                ('rii3rd', models.IntegerField(default=0)),
                ('rii4th', models.IntegerField(default=0)),
                ('opp1st', models.IntegerField(default=0)),
                ('opp2nd', models.IntegerField(default=0)),
                ('opp3rd', models.IntegerField(default=0)),
                ('opp4th', models.IntegerField(default=0)),
                ('gameSummary', models.TextField(default='There is no Game summary yet for this game.', max_length=2000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('venueName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=25)),
                ('legalName', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=2)),
                ('height', models.IntegerField(choices=[(48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82)], default=48)),
                ('weight', models.IntegerField(default=3)),
                ('birthDate', models.DateField()),
                ('birthCity', models.CharField(max_length=35)),
                ('birthState', models.CharField(max_length=2)),
                ('birthCountry', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=45)),
                ('playerBio', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925)], default=1920)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('yearSummary', models.CharField(default='', max_length=1000)),
                ('coachId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='years', to='rii_Api.Coach')),
                ('managerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='years', to='rii_Api.Manager')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ManyToManyField(to='rii_Api.Year'),
        ),
        migrations.AddField(
            model_name='game',
            name='locationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='rii_Api.Location'),
        ),
        migrations.AddField(
            model_name='game',
            name='opponentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='rii_Api.Opponent'),
        ),
        migrations.AddField(
            model_name='game',
            name='yearId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='rii_Api.Year'),
        ),
    ]
