# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rii_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='venueName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(choices=[(1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925)], default=1919),
        ),
        migrations.AlterField(
            model_name='year',
            name='yearSummary',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
