# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rii_Api', '0003_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='image',
            field=models.ImageField(default='year_images/default_year_image.jpg', upload_to='year_images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='player_images/default_player_image.jpg', upload_to='player_images/'),
        ),
    ]
