# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rii_Api', '0004_auto_20160913_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Rock Island', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(default='IL', max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='venueName',
            field=models.CharField(default='Douglas Park', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthCity',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthCountry',
            field=models.CharField(default='USA', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthState',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.CharField(default='None', max_length=45),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=170),
        ),
    ]
