# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rii_Api', '0006_auto_20160914_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerBio',
            field=models.TextField(default='There is no bio yet for this player.', max_length=2000),
        ),
    ]
