# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rii_Api', '0010_player_imageinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='imageInfo',
        ),
    ]
