# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rii_Api', '0011_remove_player_imageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='imageInfo',
            field=models.CharField(default='', max_length=90),
        ),
    ]
