# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rii_Api', '0013_auto_20160919_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='imageInfo',
            field=models.CharField(default='There is no image for this player', max_length=90),
        ),
    ]
